### ISSUE TITLE
.get() returning inherited non-existant values

### ISSUE THREAD

**Issue by Seedmanc** [nfriedly/Javascript-Flash-Cookies#35]
For example, running .get('constructor') will yield a "[class Object]" result while it should be null or undefined if there was no such entry in the database. Same applies to many other properties of the SWF object that normally are accessible via dot or square brackets, but you try to use them as the key names in .get().

**Comment by nfriedly** [comment]
Oh, good catch. It looks like .hasOwnProperty() behaves the same as in JS, so that's probably the right answer here. You want to try it out and send me a test and a patch if it does the trick?

**Comment by Seedmanc** [comment]
I added .hasOwnProperty() to getValue() in Storage.as and that apparently solves it.
However a lesser issue arose, it looks like a key with name "hasOwnProperty" can not be saved, the value of that key remains a function after calling "set". It's probably good so that the solution via that function does not fail if it was redefined, but still worth noting.

**Comment by nfriedly** [comment]
That's interesting that `hasOwnProperty` can't be overwritten. I should put a note about that in the readme.

I'll recompile it sometime soon but I think this is good for now.

It looks like I also need to fix the saucelabs tests again... Although part of me is tempted to just start testing in chrome only so that we can run the tests w/out saucelabs...

**Comment by nfriedly** [comment]
I just recompiled the swf (now ~2.5kb again), and pushed it as v2.2.2. Still need to fix the tests but I think we can call this one solved.
